name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/portfolio
            git pull origin main
            docker-compose down -v
            docker-compose up -d --build
            docker-compose exec -T laravel_app composer install
            docker-compose exec -T laravel_app php artisan key:generate
            docker-compose exec -T laravel_app php artisan migrate --force
            docker-compose exec -T laravel_app php artisan config:cache